"""create chat persistence tables

Revision ID: 06cb04c64071
Revises: 516a693a6e62
Create Date: 2026-06-16 17:57:06.297617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06cb04c64071"
down_revision: Union[str, Sequence[str], None] = "516a693a6e62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_sessions_owner_id"), "chat_sessions", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_sessions_workspace_id"),
        "chat_sessions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("message_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["chat_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_messages_owner_id"), "chat_messages", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_messages_session_id"),
        "chat_messages",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_workspace_id"),
        "chat_messages",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "chat_message_citations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("source_element_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("citation_index", sa.Integer(), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["message_id"], ["chat_messages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["chat_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_element_id"], ["source_elements.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_message_citations_document_id"),
        "chat_message_citations",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_message_citations_message_id"),
        "chat_message_citations",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_message_citations_owner_id"),
        "chat_message_citations",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_message_citations_session_id"),
        "chat_message_citations",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_message_citations_source_element_id"),
        "chat_message_citations",
        ["source_element_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_message_citations_workspace_id"),
        "chat_message_citations",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_chat_message_citations_workspace_id"),
        table_name="chat_message_citations",
    )
    op.drop_index(
        op.f("ix_chat_message_citations_source_element_id"),
        table_name="chat_message_citations",
    )
    op.drop_index(
        op.f("ix_chat_message_citations_session_id"),
        table_name="chat_message_citations",
    )
    op.drop_index(
        op.f("ix_chat_message_citations_owner_id"), table_name="chat_message_citations"
    )
    op.drop_index(
        op.f("ix_chat_message_citations_message_id"),
        table_name="chat_message_citations",
    )
    op.drop_index(
        op.f("ix_chat_message_citations_document_id"),
        table_name="chat_message_citations",
    )
    op.drop_table("chat_message_citations")
    op.drop_index(op.f("ix_chat_messages_workspace_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_session_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_owner_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_chat_sessions_workspace_id"), table_name="chat_sessions")
    op.drop_index(op.f("ix_chat_sessions_owner_id"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    # ### end Alembic commands ###
