"""add embedding to source element summaries

Revision ID: 516a693a6e62
Revises: d0074ca52c98
Create Date: 2026-06-15 12:13:52.215730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = "516a693a6e62"
down_revision: Union[str, Sequence[str], None] = "d0074ca52c98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source_element_summaries",
        sa.Column("embedding", Vector(dim=1536), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_element_summaries", "embedding")
    # ### end Alembic commands ###
