"""create source element summaries table

Revision ID: 8a12a1e785bf
Revises: 926a91530787
Create Date: 2026-06-15 11:33:58.583925

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a12a1e785bf"
down_revision: Union[str, Sequence[str], None] = "926a91530787"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_element_summaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_element_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=50), server_default="pending", nullable=False
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_element_id"], ["source_elements.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_element_summaries_document_id"),
        "source_element_summaries",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_element_summaries_owner_id"),
        "source_element_summaries",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_element_summaries_source_element_id"),
        "source_element_summaries",
        ["source_element_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_source_element_summaries_workspace_id"),
        "source_element_summaries",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_source_element_summaries_workspace_id"),
        table_name="source_element_summaries",
    )
    op.drop_index(
        op.f("ix_source_element_summaries_source_element_id"),
        table_name="source_element_summaries",
    )
    op.drop_index(
        op.f("ix_source_element_summaries_owner_id"),
        table_name="source_element_summaries",
    )
    op.drop_index(
        op.f("ix_source_element_summaries_document_id"),
        table_name="source_element_summaries",
    )
    op.drop_table("source_element_summaries")
    # ### end Alembic commands ###
