"""create source elements table

Revision ID: 926a91530787
Revises: c4b2b4e0f200
Create Date: 2026-06-11 19:05:17.592510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "926a91530787"
down_revision: Union[str, Sequence[str], None] = "c4b2b4e0f200"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_elements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("element_index", sa.Integer(), nullable=False),
        sa.Column("modality", sa.String(length=50), nullable=False),
        sa.Column("raw_content_text", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=50), server_default="completed", nullable=False
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_elements_document_id"),
        "source_elements",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_elements_owner_id"),
        "source_elements",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_elements_workspace_id"),
        "source_elements",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_elements_workspace_id"), table_name="source_elements")
    op.drop_index(op.f("ix_source_elements_owner_id"), table_name="source_elements")
    op.drop_index(op.f("ix_source_elements_document_id"), table_name="source_elements")
    op.drop_table("source_elements")
    # ### end Alembic commands ###
